package com.skniro.skniro_furniture.client;

import com.skniro.skniro_furniture.block.FurnitureKitchenBlocks;
import com.skniro.skniro_furniture.block.MapleFurnitureBlocks;
import com.skniro.skniro_furniture.block.entity.FurnitureBlockEntityType;
import com.skniro.skniro_furniture.block.renderer.CabinetBlockEntityRenderer;
import com.skniro.skniro_furniture.block.renderer.KitchenSinkBlockEntityRenderer;
import com.skniro.skniro_furniture.block.renderer.OvenBlockEntityRenderer;
import com.skniro.skniro_furniture.block.renderer.PlateBlockEntityRenderer;
import com.skniro.skniro_furniture.client.gui.screen.KitchenSinkBlockScreen;
import com.skniro.skniro_furniture.client.renderer.ChairRenderer;
import com.skniro.skniro_furniture.client.renderer.CushinoRenderer;
import com.skniro.skniro_furniture.client.renderer.SofaRenderer;
import com.skniro.skniro_furniture.entity.MapleEntityType;
import com.skniro.skniro_furniture.screen.FurnitureScreenHandlerType;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;
import net.minecraft.client.gui.screens.MenuScreens;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.blockentity.BlockEntityRenderers;

@Environment(EnvType.CLIENT)
public class MapleClient implements ClientModInitializer {
    @Override
    public void onInitializeClient() {

        RenderType renderLayer2 = RenderType.cutoutMipped();
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_OAK,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_SPRUCE,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_BIRCH,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_JUNGLE,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_ACACIA,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_DARK_OAK,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_CRIMSON,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_WARPED,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_MANGROVE,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_BAMBOO,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_CHERRY,renderLayer2);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.TABLE_PALE_OAK,renderLayer2);

        RenderType renderLayer3 = RenderType.cutout();
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_OAK, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_BIRCH, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_SPRUCE, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_JUNGLE, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_DARK_OAK, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_ACACIA, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_MANGROVE, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_CHERRY, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_CRIMSON, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_WARPED, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_PALE_OAK, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_BAMBOO, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_OAK, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_BIRCH, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_SPRUCE, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_JUNGLE, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_DARK_OAK, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_ACACIA, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_MANGROVE, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_CHERRY, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_CRIMSON, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_WARPED, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_PALE_OAK, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_BAMBOO, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_OAK_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_BIRCH_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_SPRUCE_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_JUNGLE_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_DARK_OAK_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_ACACIA_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_MANGROVE_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_CHERRY_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_CRIMSON_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_WARPED_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_PALE_OAK_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_WOOD_BAMBOO_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_OAK_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_BIRCH_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_SPRUCE_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_JUNGLE_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_DARK_OAK_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_ACACIA_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_MANGROVE_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_CHERRY_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_CRIMSON_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_WARPED_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_PALE_OAK_STYLE2, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Window_PLANK_BAMBOO_STYLE2, renderLayer3);

        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.WHITE_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.ORANGE_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.MAGENTA_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.LIGHT_BLUE_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.YELLOW_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.LIME_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.PINK_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.GRAY_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.LIGHT_GRAY_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.CYAN_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.PURPLE_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.BLUE_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.BROWN_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.GREEN_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.RED_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.BLACK_OVEN, renderLayer3);

        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.OAK_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.OAK_WOOD_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.SPRUCE_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.SPRUCE_WOOD_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.BIRCH_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.BIRCH_WOOD_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.JUNGLE_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.JUNGLE_WOOD_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.ACACIA_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.ACACIA_WOOD_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.DARK_OAK_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.DARK_OAK_WOOD_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.MANGROVE_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.MANGROVE_WOOD_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.CHERRY_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.CHERRY_WOOD_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.CRIMSON_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.CRIMSON_HYPHAE_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.WARPED_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.WARPED_HYPHAE_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.BAMBOO_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.BAMBOO_BLOCK_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.PALE_OAK_PLANKS_OVEN, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(FurnitureKitchenBlocks.PALE_OAK_WOOD_OVEN, renderLayer3);

        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.OAK_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.OAK_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.SPRUCE_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.SPRUCE_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.BIRCH_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.BIRCH_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.JUNGLE_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.JUNGLE_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.ACACIA_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.ACACIA_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DARK_OAK_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DARK_OAK_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.MANGROVE_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.MANGROVE_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.CHERRY_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.CHERRY_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.BAMBOO_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.BAMBOO_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.CRIMSON_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.CRIMSON_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.WARPED_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.WARPED_WOOD_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PALE_OAK_PLANK_Glass_TRIPLE_CABINET, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PALE_OAK_WOOD_Glass_TRIPLE_CABINET, renderLayer3);

        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.OAK_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.OAK_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.SPRUCE_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.SPRUCE_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.BIRCH_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.BIRCH_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.JUNGLE_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.JUNGLE_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.ACACIA_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.ACACIA_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DARK_OAK_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DARK_OAK_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.MANGROVE_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.MANGROVE_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.CHERRY_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.CHERRY_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.CRIMSON_HYPHAE_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.CRIMSON_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.WARPED_HYPHAE_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.WARPED_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.BAMBOO_BLOCK_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.BAMBOO_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PALE_OAK_WOOD_Glass_Four_Grid_Cabinet, renderLayer3);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PALE_OAK_PLANKS_Glass_Four_Grid_Cabinet, renderLayer3);


        RenderType renderLayer4 = RenderType.translucent();
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Black_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_White_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Orange_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Magenta_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_LightBlue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Yellow_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Lime_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Pink_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Gray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_LightGray_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Cyan_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Purple_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Blue_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Brown_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Green_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Red_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Black_Glass_Sliding_Door, renderLayer4);

        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Oak_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Spruce_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Birch_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Jungle_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Acacia_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.DarkOak_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Mangrove_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Bamboo_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Cherry_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Crimson_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.Warped_Glass_Sliding_Door, renderLayer4);
        BlockRenderLayerMap.INSTANCE.putBlock(MapleFurnitureBlocks.PaleOak_Glass_Sliding_Door, renderLayer4);

        MenuScreens.register(FurnitureScreenHandlerType.Kitchen_Sink_Block_Screen_Handler, KitchenSinkBlockScreen::new);
        registerClientEntityRenderer();
        registerClientParticle();
    }

    @Environment(EnvType.CLIENT)
    public static void registerClientEntityRenderer() {
        EntityRendererRegistry.register(MapleEntityType.CHAIR_ENTITY, ChairRenderer::new);
        EntityRendererRegistry.register(MapleEntityType.Cushion_ENTITY, CushinoRenderer::new);
        EntityRendererRegistry.register(MapleEntityType.SOFA_ENTITY, SofaRenderer::new);
        BlockEntityRenderers.register(FurnitureBlockEntityType.Cabinet_BLOCK_ENTITY, CabinetBlockEntityRenderer::new);
        BlockEntityRenderers.register(FurnitureBlockEntityType.OVEN_BLOCK_ENTITY, OvenBlockEntityRenderer::new);
        BlockEntityRenderers.register(FurnitureBlockEntityType.Kitchen_Sink_BLOCK_ENTITY, KitchenSinkBlockEntityRenderer::new);
        BlockEntityRenderers.register(FurnitureBlockEntityType.Plate_BLOCK_ENTITY, PlateBlockEntityRenderer::new);
    }

    @Environment(EnvType.CLIENT)
    public static void registerClientParticle() {

    }
}
