package com.skniro.skniro_furniture.datagen;

import com.skniro.skniro_furniture.Furniture;
import com.skniro.skniro_furniture.block.FurnitureBedroomBlocks;
import com.skniro.skniro_furniture.block.FurnitureKitchenBlocks;
import com.skniro.skniro_furniture.block.FurnitureLivingroomBlocks;
import com.skniro.skniro_furniture.block.MapleFurnitureBlocks;
import com.skniro.skniro_furniture.init.FurnitureStrings;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.core.HolderLookup;
import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;

public class MapleSimplifiedChineseLanguageProvider extends FabricLanguageProvider {
    public MapleSimplifiedChineseLanguageProvider(FabricDataOutput dataGenerator, CompletableFuture<HolderLookup.Provider> registryLookup){
        super(dataGenerator, "zh_cn", registryLookup);
    }

    @Override
    public void generateTranslations(HolderLookup.Provider wrapperLookup, TranslationBuilder translationBuilder) {

        translationBuilder.add(Furniture.Maple_Group_Furniture,"Skniro的家具");
        translationBuilder.add(Furniture.Furniture_Group_Bedroom_Furniture,"卧室家具");
        translationBuilder.add(Furniture.Furniture_Group_Kitchen_Furniture,"厨房家具");
        translationBuilder.add(Furniture.Furniture_Group_Livingroom_Furniture,"起居室家具");

        //cushion
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_WHITE,"白色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_ORANGE,"橙色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_MAGENTA,"品红色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_LIGHT_BLUE,"淡蓝色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_YELLOW,"黄色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_LIME,"黄绿色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_PINK,"粉色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_GRAY,"灰色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_LIGHT_GRAY,"淡灰色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_CYAN,"青色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_PURPLE,"紫色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_BLUE,"蓝色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_BROWN,"棕色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_GREEN,"绿色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_RED,"红色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_BLACK,"黑色橡木坐垫");

        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_WHITE, "白色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_ORANGE, "橙色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_MAGENTA, "品红色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_LIGHT_BLUE, "淡蓝色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_YELLOW, "黄色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_LIME, "黄绿色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_PINK, "粉红色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_GRAY, "灰色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_LIGHT_GRAY, "淡灰色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_CYAN, "青色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_PURPLE, "紫色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_BLUE, "蓝色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_BROWN, "棕色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_GREEN, "绿色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_RED, "红色苍白橡木垫子");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_PALE_OAK_BLACK, "黑色苍白橡木垫子");

        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_WHITE,"白色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_ORANGE,"橙色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_MAGENTA,"品红色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_LIGHT_BLUE,"淡蓝色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_YELLOW,"黄色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_LIME,"黄绿色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_PINK,"粉色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_GRAY,"灰色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_LIGHT_GRAY,"淡灰色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_CYAN,"青色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_PURPLE,"紫色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_BLUE,"蓝色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_BROWN,"棕色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_GREEN,"绿色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_RED,"红色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_BLACK,"黑色云杉木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_WHITE,"白色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_ORANGE,"橙色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_MAGENTA,"品红色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_LIGHT_BLUE,"淡蓝色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_YELLOW,"黄色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_LIME,"黄绿色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_PINK,"粉色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_GRAY,"灰色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_LIGHT_GRAY,"淡灰色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_CYAN,"青色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_PURPLE,"紫色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_BLUE,"蓝色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_BROWN,"棕色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_GREEN,"绿色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_RED,"红色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_BLACK,"黑色白桦木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_YELLOW,"黄色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_LIME,"黄绿色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_PINK,"粉色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_GRAY,"灰色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_LIGHT_GRAY,"淡灰色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_CYAN,"青色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_PURPLE,"紫色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_BLUE,"蓝色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_BROWN,"棕色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_GREEN,"绿色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_RED,"红色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_BLACK,"黑色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_WHITE,"白色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_ORANGE,"橙色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_MAGENTA,"品红色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_LIGHT_BLUE,"淡蓝色丛林木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_WHITE,"白色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_ORANGE,"橙色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_MAGENTA,"品红色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_LIGHT_BLUE,"淡蓝色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_YELLOW,"黄色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_LIME,"黄绿色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_PINK,"粉色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_GRAY,"灰色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_LIGHT_GRAY,"淡灰色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_CYAN,"青色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_PURPLE,"紫色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_BLUE,"蓝色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_BROWN,"棕色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_GREEN,"绿色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_RED,"红色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_BLACK,"黑色金合欢木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_WHITE,"白色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_ORANGE,"橙色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_MAGENTA,"品红色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIGHT_BLUE,"淡蓝色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_YELLOW,"黄色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIME,"黄绿色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_PINK,"粉色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_GRAY,"灰色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIGHT_GRAY,"淡灰色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_CYAN,"青色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_PURPLE,"紫色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_BLUE,"蓝色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_BROWN,"棕色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_GREEN,"绿色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_RED,"红色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_BLACK,"黑色深色橡木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_WHITE,"白色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_ORANGE,"橙色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_MAGENTA,"品红色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_LIGHT_BLUE,"淡蓝色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_YELLOW,"黄色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_LIME,"黄绿色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_PINK,"粉色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_GRAY,"灰色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_LIGHT_GRAY,"淡灰色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_CYAN,"青色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_PURPLE,"紫色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_BLUE,"蓝色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_BROWN,"棕色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_GREEN,"绿色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_RED,"红色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_BLACK,"黑色绯红木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_WHITE,"白色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_ORANGE,"橙色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_MAGENTA,"品红色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_LIGHT_BLUE,"淡蓝色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_YELLOW,"黄色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_LIME,"黄绿色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_PINK,"粉色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_GRAY,"灰色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_LIGHT_GRAY,"淡灰色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_CYAN,"青色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_PURPLE,"紫色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_BLUE,"蓝色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_BROWN,"棕色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_GREEN,"绿色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_RED,"红色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_BLACK,"黑色诡异木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_WHITE,"白色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_ORANGE,"橙色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_MAGENTA,"品红色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_LIGHT_BLUE,"淡蓝色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_YELLOW,"黄色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_LIME,"黄绿色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_PINK,"粉色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_GRAY,"灰色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_LIGHT_GRAY,"淡灰色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_CYAN,"青色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_PURPLE,"紫色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_BLUE,"蓝色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_BROWN,"棕色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_GREEN,"绿色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_RED,"红色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_BLACK,"黑色红树木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_WHITE,"白色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_ORANGE,"橙色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_MAGENTA,"品红色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_LIGHT_BLUE,"淡蓝色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_YELLOW,"黄色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_LIME,"黄绿色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_PINK,"粉色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_GRAY,"灰色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_LIGHT_GRAY,"淡灰色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_CYAN,"青色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_PURPLE,"紫色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_BLUE,"蓝色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_BROWN,"棕色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_GREEN,"绿色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_RED,"红色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_BLACK,"黑色樱花木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_WHITE,"白色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_ORANGE,"橙色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_MAGENTA,"品红色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_LIGHT_BLUE,"淡蓝色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_YELLOW,"黄色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_LIME,"黄绿色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_PINK,"粉色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_GRAY,"灰色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_LIGHT_GRAY,"淡灰色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_CYAN,"青色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_PURPLE,"紫色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_BLUE,"蓝色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_BROWN,"棕色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_GREEN,"绿色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_RED,"红色竹木坐垫");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_BLACK,"黑色竹木坐垫");


        //Table
        translationBuilder.add(MapleFurnitureBlocks.TABLE_OAK,"橡木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_SPRUCE,"云杉木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_BIRCH,"白桦木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_JUNGLE,"丛林木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_ACACIA,"金合欢木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_DARK_OAK,"深色橡木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_CRIMSON,"绯红木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_WARPED,"诡异木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_MANGROVE,"红树木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_BAMBOO,"竹木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_CHERRY,"樱花木桌");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_PALE_OAK, "苍白橡木桌");

        //Window
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_OAK,"橡木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_BIRCH,"白桦木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_SPRUCE,"云杉木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_JUNGLE,"丛林木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_DARK_OAK,"深色橡木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_ACACIA,"金合欢木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_MANGROVE,"红树木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_CHERRY,"樱花木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_CRIMSON,"绯红木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_WARPED,"诡异木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_OAK,"橡木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_BIRCH,"白桦木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_SPRUCE,"云杉木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_JUNGLE,"丛林木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_DARK_OAK,"深色橡木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_ACACIA,"金合欢木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_MANGROVE,"红树木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_CHERRY,"樱花木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_CRIMSON,"绯红木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_WARPED,"诡异木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_PALE_OAK, "苍白橡木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_BAMBOO, "竹木窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_PALE_OAK, "苍白橡木板窗");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_BAMBOO, "竹木板窗");

        //CoffeeTable
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_OAK,"橡木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_SPRUCE,"云杉木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_BIRCH,"白桦木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_JUNGLE,"丛林木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_ACACIA,"金合欢木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_DARK_OAK,"深色橡木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_CRIMSON,"绯红木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_WARPED,"诡异木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_MANGROVE,"红树木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_BAMBOO,"竹木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_CHERRY,"樱木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_OAK,"橡木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_SPRUCE,"云杉木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_BIRCH,"白桦木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_JUNGLE,"丛林木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_ACACIA,"金合欢木板咖啡桌");;
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_DARK_OAK,"深色橡木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_CRIMSON,"绯红木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_WARPED,"诡异木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_MANGROVE,"红树木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_BAMBOO,"竹木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_CHERRY,"樱木板咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_PALE_OAK, "苍白橡木咖啡桌");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_PALE_OAK, "苍白橡木板咖啡桌");


        //Chair
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_OAK,"橡木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_SPRUCE,"云杉木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_BIRCH,"白桦木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_JUNGLE,"丛林木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_ACACIA,"金合欢木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_DARK_OAK,"深色橡木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_CRIMSON,"绯红木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_WARPED,"诡异木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_MANGROVE,"红树木椅子");;
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_BAMBOO,"竹木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_CHERRY,"樱木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_OAK,"橡木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_SPRUCE,"云杉木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_BIRCH,"白桦木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_JUNGLE,"丛林木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_ACACIA,"金合欢木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_DARK_OAK,"深色橡木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_CRIMSON,"绯红木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_WARPED,"诡异木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_MANGROVE,"红树木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_BAMBOO,"竹木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_CHERRY,"樱木板椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_PALE_OAK, "苍白橡木椅子");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_PALE_OAK, "苍白橡木板椅子");

        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_OAK,"橡木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_SPRUCE,"云杉木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_BIRCH,"白桦木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_JUNGLE,"丛林木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_ACACIA,"金合欢木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_DARK_OAK,"深色橡木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_CRIMSON,"绯红木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_WARPED,"诡异木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_MANGROVE,"红树木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_BAMBOO,"竹木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_CHERRY,"樱木板茶几");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_PALE_OAK, "苍白橡木茶几");

        translationBuilder.add(FurnitureBedroomBlocks.OAK_PLANKS_BEDSIDE_CABINET, "橡木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.OAK_WOOD_BEDSIDE_CABINET, "橡木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.PALE_OAK_PLANKS_BEDSIDE_CABINET, "苍白橡木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.PALE_OAK_WOOD_BEDSIDE_CABINET, "苍白橡木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.SPRUCE_PLANKS_BEDSIDE_CABINET, "云杉木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.SPRUCE_WOOD_BEDSIDE_CABINET, "云杉木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.BIRCH_PLANKS_BEDSIDE_CABINET, "桦木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.BIRCH_WOOD_BEDSIDE_CABINET, "桦木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.JUNGLE_PLANKS_BEDSIDE_CABINET, "丛林木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.JUNGLE_WOOD_BEDSIDE_CABINET, "丛林木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.ACACIA_PLANKS_BEDSIDE_CABINET, "金合欢木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.ACACIA_WOOD_BEDSIDE_CABINET, "金合欢木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.DARK_OAK_PLANKS_BEDSIDE_CABINET, "深色橡木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.DARK_OAK_WOOD_BEDSIDE_CABINET, "深色橡木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.MANGROVE_PLANKS_BEDSIDE_CABINET, "红树林木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.MANGROVE_WOOD_BEDSIDE_CABINET, "红树林木床柜");
        translationBuilder.add(FurnitureBedroomBlocks.CHERRY_PLANKS_BEDSIDE_CABINET, "樱桃木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.CHERRY_WOOD_BEDSIDE_CABINET, "樱桃木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.CRIMSON_PLANKS_BEDSIDE_CABINET, "绯红木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.CRIMSON_HYPHAE_BEDSIDE_CABINET, "绯红木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.WARPED_PLANKS_BEDSIDE_CABINET, "弯曲板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.WARPED_HYPHAE_BEDSIDE_CABINET, "诡异木床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.BAMBOO_PLANKS_BEDSIDE_CABINET, "竹木板床头柜");
        translationBuilder.add(FurnitureBedroomBlocks.BAMBOO_BLOCK_BEDSIDE_CABINET, "竹木床头柜");

        translationBuilder.add(FurnitureBedroomBlocks.OAK_PLANKS_Desk_CABINET, "橡木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.OAK_WOOD_Desk_CABINET, "橡木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.PALE_OAK_PLANKS_Desk_CABINET, "苍白橡木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.PALE_OAK_WOOD_Desk_CABINET, "苍白橡木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.SPRUCE_PLANKS_Desk_CABINET, "云杉木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.SPRUCE_WOOD_Desk_CABINET, "云杉木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.BIRCH_PLANKS_Desk_CABINET, "桦木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.BIRCH_WOOD_Desk_CABINET, "桦木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.JUNGLE_PLANKS_Desk_CABINET, "丛林木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.JUNGLE_WOOD_Desk_CABINET, "丛林木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.ACACIA_PLANKS_Desk_CABINET, "金合欢木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.ACACIA_WOOD_Desk_CABINET, "金合欢木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.DARK_OAK_PLANKS_Desk_CABINET, "深色橡木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.DARK_OAK_WOOD_Desk_CABINET, "深色橡木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.MANGROVE_PLANKS_Desk_CABINET, "红树林木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.MANGROVE_WOOD_Desk_CABINET, "红树林木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.CHERRY_PLANKS_Desk_CABINET, "樱桃木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.CHERRY_WOOD_Desk_CABINET, "樱桃木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.CRIMSON_PLANKS_Desk_CABINET, "绯红木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.CRIMSON_HYPHAE_Desk_CABINET, "绯红木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.WARPED_PLANKS_Desk_CABINET, "诡异木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.WARPED_HYPHAE_Desk_CABINET, "诡异木桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.BAMBOO_PLANKS_Desk_CABINET, "竹木板桌柜");
        translationBuilder.add(FurnitureBedroomBlocks.BAMBOO_BLOCK_Desk_CABINET, "竹木桌橱柜");

        translationBuilder.add(FurnitureBedroomBlocks.OAK_PLANKS_BOOK_Desk, "橡木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.OAK_WOOD_BOOK_Desk, "橡木书桌");
        translationBuilder.add(FurnitureBedroomBlocks.PALE_OAK_PLANKS_BOOK_Desk, "苍白橡木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.PALE_OAK_WOOD_BOOK_Desk, "苍白橡木书桌");
        translationBuilder.add(FurnitureBedroomBlocks.SPRUCE_PLANKS_BOOK_Desk, "云杉木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.SPRUCE_WOOD_BOOK_Desk, "云杉木书桌");
        translationBuilder.add(FurnitureBedroomBlocks.BIRCH_PLANKS_BOOK_Desk, "桦木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.BIRCH_WOOD_BOOK_Desk, "桦木头书桌");
        translationBuilder.add(FurnitureBedroomBlocks.JUNGLE_PLANKS_BOOK_Desk, "丛林木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.JUNGLE_WOOD_BOOK_Desk, "丛林木头书桌");
        translationBuilder.add(FurnitureBedroomBlocks.ACACIA_PLANKS_BOOK_Desk, "金合欢木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.ACACIA_WOOD_BOOK_Desk, "金合欢木书桌");
        translationBuilder.add(FurnitureBedroomBlocks.DARK_OAK_PLANKS_BOOK_Desk, "深色橡木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.DARK_OAK_WOOD_BOOK_Desk, "黑橡木头书桌");
        translationBuilder.add(FurnitureBedroomBlocks.MANGROVE_PLANKS_BOOK_Desk, "红树林木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.MANGROVE_WOOD_BOOK_Desk, "红树林木头书桌");
        translationBuilder.add(FurnitureBedroomBlocks.CHERRY_PLANKS_BOOK_Desk, "樱桃木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.CHERRY_WOOD_BOOK_Desk, "樱桃木书桌");
        translationBuilder.add(FurnitureBedroomBlocks.CRIMSON_PLANKS_BOOK_Desk, "绯红木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.CRIMSON_HYPHAE_BOOK_Desk, "绯红木书桌");
        translationBuilder.add(FurnitureBedroomBlocks.WARPED_PLANKS_BOOK_Desk, "诡异木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.WARPED_HYPHAE_BOOK_Desk, "诡异木头书桌");
        translationBuilder.add(FurnitureBedroomBlocks.BAMBOO_PLANKS_BOOK_Desk, "竹木板书桌");
        translationBuilder.add(FurnitureBedroomBlocks.BAMBOO_BLOCK_BOOK_Desk, "竹木书桌");

        translationBuilder.add(FurnitureKitchenBlocks.WHITE_OVEN, "白烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.ORANGE_OVEN, "橙烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.MAGENTA_OVEN, "品红色烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_BLUE_OVEN, "淡蓝色烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.YELLOW_OVEN, "黄烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.LIME_OVEN, "石灰烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.PINK_OVEN, "粉红色烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.GRAY_OVEN, "灰烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_GRAY_OVEN, "淡灰色烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.CYAN_OVEN, "青色烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.PURPLE_OVEN, "紫色烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.BLUE_OVEN, "蓝烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.BROWN_OVEN, "棕色烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.GREEN_OVEN, "绿烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.RED_OVEN, "红烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.BLACK_OVEN, "黑色烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_PLANKS_OVEN, "橡木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_WOOD_OVEN, "橡木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_PLANKS_OVEN, "苍白橡木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_WOOD_OVEN, "苍白橡木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_PLANKS_OVEN, "云杉木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_WOOD_OVEN, "云杉木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_PLANKS_OVEN, "桦木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_WOOD_OVEN, "桦木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_PLANKS_OVEN, "丛林木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_WOOD_OVEN, "丛林木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_PLANKS_OVEN, "金合欢木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_WOOD_OVEN, "金合欢木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_PLANKS_OVEN, "深色橡木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_WOOD_OVEN, "黑橡木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_PLANKS_OVEN, "红树林木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_WOOD_OVEN, "红树林木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_PLANKS_OVEN, "樱桃木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_WOOD_OVEN, "樱桃木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_PLANKS_OVEN, "绯红木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_HYPHAE_OVEN, "绯红木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_PLANKS_OVEN, "弯曲板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_HYPHAE_OVEN, "诡异木烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_PLANKS_OVEN, "竹木板烤箱");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_BLOCK_OVEN, "竹木烤箱");

        translationBuilder.add(FurnitureKitchenBlocks.WHITE_KITCHEN_COUNTER, "白色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.ORANGE_KITCHEN_COUNTER, "橙色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.MAGENTA_KITCHEN_COUNTER, "品红色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_BLUE_KITCHEN_COUNTER, "淡蓝色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.YELLOW_KITCHEN_COUNTER, "黄色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.LIME_KITCHEN_COUNTER, "石灰厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.PINK_KITCHEN_COUNTER, "粉红色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.GRAY_KITCHEN_COUNTER, "灰色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_GRAY_KITCHEN_COUNTER, "淡灰色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.CYAN_KITCHEN_COUNTER, "青色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.PURPLE_KITCHEN_COUNTER, "紫色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.BLUE_KITCHEN_COUNTER, "蓝色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.BROWN_KITCHEN_COUNTER, "棕色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.GREEN_KITCHEN_COUNTER, "绿色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.RED_KITCHEN_COUNTER, "红色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.BLACK_KITCHEN_COUNTER, "黑色厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_PLANKS_KITCHEN_COUNTER, "橡木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_WOOD_KITCHEN_COUNTER, "橡木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_PLANKS_KITCHEN_COUNTER, "苍白橡木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_WOOD_KITCHEN_COUNTER, "苍白橡木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_PLANKS_KITCHEN_COUNTER, "云杉木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_WOOD_KITCHEN_COUNTER, "云杉木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_PLANKS_KITCHEN_COUNTER, "桦木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_WOOD_KITCHEN_COUNTER, "桦木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_PLANKS_KITCHEN_COUNTER, "丛林木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_WOOD_KITCHEN_COUNTER, "丛林木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_PLANKS_KITCHEN_COUNTER, "金合欢木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_WOOD_KITCHEN_COUNTER, "金合欢木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_PLANKS_KITCHEN_COUNTER, "深色橡木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_WOOD_KITCHEN_COUNTER, "深色橡木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_PLANKS_KITCHEN_COUNTER, "红树林木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_WOOD_KITCHEN_COUNTER, "红树林木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_PLANKS_KITCHEN_COUNTER, "樱桃木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_WOOD_KITCHEN_COUNTER, "樱桃木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_PLANKS_KITCHEN_COUNTER, "绯红木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_HYPHAE_KITCHEN_COUNTER, "绯红木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_PLANKS_KITCHEN_COUNTER, "诡异木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_HYPHAE_KITCHEN_COUNTER, "诡异木厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_PLANKS_KITCHEN_COUNTER, "竹木板厨房柜台");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_BLOCK_KITCHEN_COUNTER, "竹木厨房柜台");

        translationBuilder.add(FurnitureKitchenBlocks.WHITE_KITCHEN_COUNTER_DRAWER, "白色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.ORANGE_KITCHEN_COUNTER_DRAWER, "橙色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.MAGENTA_KITCHEN_COUNTER_DRAWER, "品红色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_BLUE_KITCHEN_COUNTER_DRAWER, "淡蓝色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.YELLOW_KITCHEN_COUNTER_DRAWER, "黄色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.LIME_KITCHEN_COUNTER_DRAWER, "石灰厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.PINK_KITCHEN_COUNTER_DRAWER, "粉红色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.GRAY_KITCHEN_COUNTER_DRAWER, "灰色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_GRAY_KITCHEN_COUNTER_DRAWER, "淡灰色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.CYAN_KITCHEN_COUNTER_DRAWER, "青色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.PURPLE_KITCHEN_COUNTER_DRAWER, "紫色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.BLUE_KITCHEN_COUNTER_DRAWER, "蓝色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.BROWN_KITCHEN_COUNTER_DRAWER, "棕色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.GREEN_KITCHEN_COUNTER_DRAWER, "绿色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.RED_KITCHEN_COUNTER_DRAWER, "红色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.BLACK_KITCHEN_COUNTER_DRAWER, "黑色厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_PLANKS_KITCHEN_COUNTER_DRAWER, "橡木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_WOOD_KITCHEN_COUNTER_DRAWER, "橡木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_PLANKS_KITCHEN_COUNTER_DRAWER, "苍白橡木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_WOOD_KITCHEN_COUNTER_DRAWER, "苍白橡木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_PLANKS_KITCHEN_COUNTER_DRAWER, "云杉木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_WOOD_KITCHEN_COUNTER_DRAWER, "云杉木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_PLANKS_KITCHEN_COUNTER_DRAWER, "桦木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_WOOD_KITCHEN_COUNTER_DRAWER, "桦木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_PLANKS_KITCHEN_COUNTER_DRAWER, "丛林木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_WOOD_KITCHEN_COUNTER_DRAWER, "丛林木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_PLANKS_KITCHEN_COUNTER_DRAWER, "金合欢木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_WOOD_KITCHEN_COUNTER_DRAWER, "金合欢木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_PLANKS_KITCHEN_COUNTER_DRAWER, "深色橡木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_WOOD_KITCHEN_COUNTER_DRAWER, "深色橡木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_PLANKS_KITCHEN_COUNTER_DRAWER, "红树林木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_WOOD_KITCHEN_COUNTER_DRAWER, "红树林木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_PLANKS_KITCHEN_COUNTER_DRAWER, "樱桃木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_WOOD_KITCHEN_COUNTER_DRAWER, "樱桃木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_PLANKS_KITCHEN_COUNTER_DRAWER, "绯红木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_HYPHAE_KITCHEN_COUNTER_DRAWER, "绯红木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_PLANKS_KITCHEN_COUNTER_DRAWER, "诡异木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_HYPHAE_KITCHEN_COUNTER_DRAWER, "诡异木厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_PLANKS_KITCHEN_COUNTER_DRAWER, "竹木板厨房柜台抽屉");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_BLOCK_KITCHEN_COUNTER_DRAWER, "竹木厨房柜台抽屉");

        translationBuilder.add(FurnitureKitchenBlocks.WHITE_KITCHEN_CABINET, "白色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.ORANGE_KITCHEN_CABINET, "橙色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.MAGENTA_KITCHEN_CABINET, "品红色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_BLUE_KITCHEN_CABINET, "淡蓝色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.YELLOW_KITCHEN_CABINET, "黄色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.LIME_KITCHEN_CABINET, "石灰厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.PINK_KITCHEN_CABINET, "粉红色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.GRAY_KITCHEN_CABINET, "灰色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_GRAY_KITCHEN_CABINET, "淡灰色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.CYAN_KITCHEN_CABINET, "青色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.PURPLE_KITCHEN_CABINET, "紫色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.BLUE_KITCHEN_CABINET, "蓝色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.BROWN_KITCHEN_CABINET, "棕色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.GREEN_KITCHEN_CABINET, "绿色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.RED_KITCHEN_CABINET, "红色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.BLACK_KITCHEN_CABINET, "黑色厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_PLANKS_KITCHEN_CABINET, "橡木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_WOOD_KITCHEN_CABINET, "橡木厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_PLANKS_KITCHEN_CABINET, "苍白橡木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_WOOD_KITCHEN_CABINET, "苍白橡木厨房柜");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_PLANKS_KITCHEN_CABINET, "云杉木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_WOOD_KITCHEN_CABINET, "云杉木厨房柜");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_PLANKS_KITCHEN_CABINET, "桦木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_WOOD_KITCHEN_CABINET, "桦木柜");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_PLANKS_KITCHEN_CABINET, "丛林木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_WOOD_KITCHEN_CABINET, "丛林木柜");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_PLANKS_KITCHEN_CABINET, "金合欢木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_WOOD_KITCHEN_CABINET, "金合欢木厨房柜");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_PLANKS_KITCHEN_CABINET, "深色橡木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_WOOD_KITCHEN_CABINET, "深色橡木柜");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_PLANKS_KITCHEN_CABINET, "红树林木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_WOOD_KITCHEN_CABINET, "红树林木柜");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_PLANKS_KITCHEN_CABINET, "樱桃木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_WOOD_KITCHEN_CABINET, "樱桃木厨房柜");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_PLANKS_KITCHEN_CABINET, "绯红木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_HYPHAE_KITCHEN_CABINET, "深红木厨房柜");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_PLANKS_KITCHEN_CABINET, "诡异木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_HYPHAE_KITCHEN_CABINET, "诡异木厨房柜");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_PLANKS_KITCHEN_CABINET, "竹木板厨柜");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_BLOCK_KITCHEN_CABINET, "竹木厨柜");

        translationBuilder.add(FurnitureKitchenBlocks.WHITE_Fridge, "白冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.ORANGE_Fridge, "橙色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.MAGENTA_Fridge, "品红色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_BLUE_Fridge, "淡蓝色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.YELLOW_Fridge, "黄色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.LIME_Fridge, "石灰冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.PINK_Fridge, "粉红色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.GRAY_Fridge, "灰色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_GRAY_Fridge, "淡灰色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.CYAN_Fridge, "青色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.PURPLE_Fridge, "紫色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.BLUE_Fridge, "蓝色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.BROWN_Fridge, "棕色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.GREEN_Fridge, "绿色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.RED_Fridge, "红色冰箱");
        translationBuilder.add(FurnitureKitchenBlocks.BLACK_Fridge, "黑色冰箱");

        translationBuilder.add(FurnitureKitchenBlocks.WHITE_KITCHEN_SINK, "白色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.ORANGE_KITCHEN_SINK, "橙色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.MAGENTA_KITCHEN_SINK, "品红色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_BLUE_KITCHEN_SINK, "淡蓝色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.YELLOW_KITCHEN_SINK, "黄色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.LIME_KITCHEN_SINK, "石灰厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.PINK_KITCHEN_SINK, "粉红色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.GRAY_KITCHEN_SINK, "灰色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.LIGHT_GRAY_KITCHEN_SINK, "淡灰色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.CYAN_KITCHEN_SINK, "青色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.PURPLE_KITCHEN_SINK, "紫色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.BLUE_KITCHEN_SINK, "蓝色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.BROWN_KITCHEN_SINK, "棕色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.GREEN_KITCHEN_SINK, "绿色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.RED_KITCHEN_SINK, "红色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.BLACK_KITCHEN_SINK, "黑色厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_PLANKS_KITCHEN_SINK, "橡木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.OAK_WOOD_KITCHEN_SINK, "橡木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_PLANKS_KITCHEN_SINK, "苍白橡木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.PALE_OAK_WOOD_KITCHEN_SINK, "苍白橡木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_PLANKS_KITCHEN_SINK, "云杉木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.SPRUCE_WOOD_KITCHEN_SINK, "云杉木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_PLANKS_KITCHEN_SINK, "桦木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.BIRCH_WOOD_KITCHEN_SINK, "桦木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_PLANKS_KITCHEN_SINK, "丛林木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.JUNGLE_WOOD_KITCHEN_SINK, "丛林木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_PLANKS_KITCHEN_SINK, "金合欢木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.ACACIA_WOOD_KITCHEN_SINK, "金合欢木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_PLANKS_KITCHEN_SINK, "深色橡木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.DARK_OAK_WOOD_KITCHEN_SINK, "黑橡木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_PLANKS_KITCHEN_SINK, "红树林木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.MANGROVE_WOOD_KITCHEN_SINK, "红树林木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_PLANKS_KITCHEN_SINK, "樱桃木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.CHERRY_WOOD_KITCHEN_SINK, "樱桃木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_PLANKS_KITCHEN_SINK, "绯红木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.CRIMSON_HYPHAE_KITCHEN_SINK, "绯红木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_PLANKS_KITCHEN_SINK, "诡异木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.WARPED_HYPHAE_KITCHEN_SINK, "诡异木厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_PLANKS_KITCHEN_SINK, "竹木板厨房水槽");
        translationBuilder.add(FurnitureKitchenBlocks.BAMBOO_BLOCK_KITCHEN_SINK, "竹木厨房水槽");

        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_WHITE, "白色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_ORANGE, "橙色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_MAGENTA, "品红色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_LIGHT_BLUE, "淡蓝色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_YELLOW, "黄色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_LIME, "石灰沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_PINK, "粉红色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_GRAY, "灰色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_LIGHT_GRAY, "淡灰色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_CYAN, "黄色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_PURPLE, "紫色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_BLUE, "蓝色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_BROWN, "棕色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_GREEN, "绿色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_RED, "红色沙发");
        translationBuilder.add(FurnitureLivingroomBlocks.Sofa_BLACK, "黑色沙发");

        translationBuilder.add(FurnitureLivingroomBlocks.OAK_PLANKS_TV_STAND, "橡木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.OAK_WOOD_TV_STAND, "橡木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.PALE_OAK_PLANKS_TV_STAND, "苍白橡木板电视摊");
        translationBuilder.add(FurnitureLivingroomBlocks.PALE_OAK_WOOD_TV_STAND, "苍白橡木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.SPRUCE_PLANKS_TV_STAND, "云杉木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.SPRUCE_WOOD_TV_STAND, "云杉木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.BIRCH_PLANKS_TV_STAND, "桦木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.BIRCH_WOOD_TV_STAND, "桦木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.JUNGLE_PLANKS_TV_STAND, "丛林木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.JUNGLE_WOOD_TV_STAND, "丛林木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.ACACIA_PLANKS_TV_STAND, "金合欢木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.ACACIA_WOOD_TV_STAND, "金合欢木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.DARK_OAK_PLANKS_TV_STAND, "深色橡木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.DARK_OAK_WOOD_TV_STAND, "深色橡木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.MANGROVE_PLANKS_TV_STAND, "红树林木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.MANGROVE_WOOD_TV_STAND, "红树林木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.CHERRY_PLANKS_TV_STAND, "樱桃木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.CHERRY_WOOD_TV_STAND, "樱桃木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.CRIMSON_PLANKS_TV_STAND, "绯红木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.CRIMSON_HYPHAE_TV_STAND, "绯红木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.WARPED_PLANKS_TV_STAND, "诡异木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.WARPED_HYPHAE_TV_STAND, "诡异木电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.BAMBOO_PLANKS_TV_STAND, "竹木板电视柜");
        translationBuilder.add(FurnitureLivingroomBlocks.BAMBOO_BLOCK_TV_STAND, "竹木电视柜");





        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_OAK_STYLE2, "橡木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_PALE_OAK_STYLE2, "苍白橡木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_BIRCH_STYLE2, "桦木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_SPRUCE_STYLE2, "云杉木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_JUNGLE_STYLE2, "丛林木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_DARK_OAK_STYLE2, "深色橡木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_ACACIA_STYLE2, "金合欢木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_MANGROVE_STYLE2, "红树林木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_CHERRY_STYLE2, "樱桃木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_BAMBOO_STYLE2, "竹木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_CRIMSON_STYLE2, "绯红木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_WARPED_STYLE2, "诡异木窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_OAK_STYLE2, "橡木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_PALE_OAK_STYLE2, "苍白橡木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_BIRCH_STYLE2, "桦木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_SPRUCE_STYLE2, "云杉木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_JUNGLE_STYLE2, "丛林木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_DARK_OAK_STYLE2, "深色橡木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_ACACIA_STYLE2, "金合欢木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_MANGROVE_STYLE2, "红树林木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_CHERRY_STYLE2, "樱桃木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_BAMBOO_STYLE2, "竹板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_CRIMSON_STYLE2, "绯红木板窗（样式2）");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_WARPED_STYLE2, "诡异木板窗（样式2）");



        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_WHITE, "白色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_ORANGE, "橙色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_MAGENTA, "品红色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_YELLOW, "黄色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_LIME, "橡木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_PINK, "粉红色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_GRAY, "灰色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_CYAN, "青色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_PURPLE, "紫色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_BLUE, "蓝色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_BROWN, "棕色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_GREEN, "绿色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_RED, "红色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_COFFEE_CHAIR_BLACK, "黑色橡木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_WHITE, "白色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_ORANGE, "橙色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_MAGENTA, "品红色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_YELLOW, "黄色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_LIME, "苍白橡木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_PINK, "粉红色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_GRAY, "灰色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_CYAN, "青色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_PURPLE, "紫色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_BLUE, "蓝色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_BROWN, "棕色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_GREEN, "绿色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_RED, "红色苍白橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_COFFEE_CHAIR_BLACK, "黑色苍白橡木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_WHITE, "白色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_ORANGE, "橙色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_MAGENTA, "品红色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_YELLOW, "黄色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_LIME, "云杉木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_PINK, "粉红色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_GRAY, "灰色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_CYAN, "青色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_PURPLE, "紫色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_BLUE, "蓝色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_BROWN, "棕色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_GREEN, "绿色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_RED, "红色云杉木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_COFFEE_CHAIR_BLACK, "黑色云杉木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_WHITE, "白色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_ORANGE, "橙色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_MAGENTA, "品红色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_YELLOW, "黄色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_LIME, "桦木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_PINK, "粉红色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_GRAY, "灰色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_CYAN, "青色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_PURPLE, "紫色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_BLUE, "蓝色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_BROWN, "棕色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_GREEN, "绿色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_RED, "红色桦木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_COFFEE_CHAIR_BLACK, "黑色桦木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_WHITE, "白色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_ORANGE, "橙色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_MAGENTA, "品红色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_YELLOW, "黄色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_LIME, "丛林木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_PINK, "粉红色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_GRAY, "灰色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_CYAN, "青色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_PURPLE, "紫色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_BLUE, "蓝色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_BROWN, "棕色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_GREEN, "绿色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_RED, "红色丛林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_COFFEE_CHAIR_BLACK, "黑色丛林木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_WHITE, "白色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_ORANGE, "橙色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_MAGENTA, "品红色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_YELLOW, "黄色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_LIME, "金合欢木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_PINK, "粉红色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_GRAY, "灰色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_CYAN, "青色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_PURPLE, "紫色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_BLUE, "蓝色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_BROWN, "棕色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_GREEN, "绿色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_RED, "红色金合欢木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_COFFEE_CHAIR_BLACK, "黑色金合欢木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_WHITE, "白色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_ORANGE, "橙色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_MAGENTA, "品红色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_YELLOW, "黄色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_LIME, "深色橡木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_PINK, "粉红色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_GRAY, "灰色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_CYAN, "青色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_PURPLE, "紫色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_BLUE, "蓝色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_BROWN, "棕色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_GREEN, "绿色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_RED, "红色深色橡木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_COFFEE_CHAIR_BLACK, "黑色深色橡木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_WHITE, "白色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_ORANGE, "橙色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_MAGENTA, "品红色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_YELLOW, "黄色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_LIME, "红树林木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_PINK, "粉红色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_GRAY, "灰色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_CYAN, "青色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_PURPLE, "紫色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_BLUE, "蓝色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_BROWN, "棕色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_GREEN, "绿色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_RED, "红色红树林木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_COFFEE_CHAIR_BLACK, "黑色红树林木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_WHITE, "白色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_ORANGE, "橙色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_MAGENTA, "品红色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_YELLOW, "黄色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_LIME, "樱桃木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_PINK, "粉红色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_GRAY, "灰色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_CYAN, "青色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_PURPLE, "紫色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_BLUE, "蓝色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_BROWN, "棕色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_GREEN, "绿色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_RED, "红色樱桃木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_COFFEE_CHAIR_BLACK, "黑色樱桃木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_WHITE, "白色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_ORANGE, "橙色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_MAGENTA, "品红色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_YELLOW, "黄色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_LIME, "竹板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_PINK, "粉红色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_GRAY, "灰色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_CYAN, "青色竹板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_PURPLE, "紫色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_BLUE, "蓝色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_BROWN, "棕色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_GREEN, "绿色竹木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_RED, "红色竹板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_COFFEE_CHAIR_BLACK, "黑色竹木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_WHITE, "白色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_ORANGE, "橙色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_MAGENTA, "品红色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_YELLOW, "黄色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_LIME, "青色绯红木板咖啡椅石灰");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_PINK, "粉红色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_GRAY, "灰色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_CYAN, "青色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_PURPLE, "紫色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_BLUE, "蓝色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_BROWN, "棕色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_GREEN, "绿色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_RED, "红色绯红木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_COFFEE_CHAIR_BLACK, "黑色绯红木板咖啡椅");

        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_WHITE, "白色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_ORANGE, "橙色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_MAGENTA, "品红色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_LIGHT_BLUE, "淡蓝色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_YELLOW, "黄色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_LIME, "青色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_PINK, "粉红色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_GRAY, "灰色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_LIGHT_GRAY, "淡灰色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_CYAN, "青色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_PURPLE, "紫色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_BLUE, "蓝色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_BROWN, "棕色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_GREEN, "绿色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_RED, "红色诡异木板咖啡椅");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_COFFEE_CHAIR_BLACK, "黑色诡异木板咖啡椅");


        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_TRIPLE_CABINET, "橡木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.OAK_WOOD_TRIPLE_CABINET, "橡木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_TRIPLE_CABINET, "苍白橡木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_WOOD_TRIPLE_CABINET, "苍白橡木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_TRIPLE_CABINET, "云杉木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_WOOD_TRIPLE_CABINET, "云杉木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_TRIPLE_CABINET, "桦木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_WOOD_TRIPLE_CABINET, "桦木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_TRIPLE_CABINET, "丛林木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_WOOD_TRIPLE_CABINET, "丛林木柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_TRIPLE_CABINET, "金合欢木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_WOOD_TRIPLE_CABINET, "金合欢木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_TRIPLE_CABINET, "深色橡木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_WOOD_TRIPLE_CABINET, "黑橡木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_TRIPLE_CABINET, "红树林木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_WOOD_TRIPLE_CABINET, "红树林木柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_TRIPLE_CABINET, "樱桃木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_WOOD_TRIPLE_CABINET, "樱桃木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_TRIPLE_CABINET, "竹木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_WOOD_TRIPLE_CABINET, "竹木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_TRIPLE_CABINET, "绯红木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_WOOD_TRIPLE_CABINET, "深红木三格柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_TRIPLE_CABINET, "诡异木板三格柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_WOOD_TRIPLE_CABINET, "诡异木三格柜");

        translationBuilder.add(MapleFurnitureBlocks.OAK_WOOD_Four_Grid_Cabinet, "橡木四格柜");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANKS_Four_Grid_Cabinet, "橡木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_WOOD_Four_Grid_Cabinet, "苍白橡木柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANKS_Four_Grid_Cabinet, "苍白橡木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_WOOD_Four_Grid_Cabinet, "云杉木四格柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANKS_Four_Grid_Cabinet, "云杉木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_WOOD_Four_Grid_Cabinet, "桦木四格柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANKS_Four_Grid_Cabinet, "桦木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_WOOD_Four_Grid_Cabinet, "丛林木柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANKS_Four_Grid_Cabinet, "丛林木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_WOOD_Four_Grid_Cabinet, "金合欢木四格柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANKS_Four_Grid_Cabinet, "金合欢木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_WOOD_Four_Grid_Cabinet, "深色橡木柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANKS_Four_Grid_Cabinet, "深色橡木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_WOOD_Four_Grid_Cabinet, "红树林木柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANKS_Four_Grid_Cabinet, "红树林木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_WOOD_Four_Grid_Cabinet, "樱桃木四格柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANKS_Four_Grid_Cabinet, "樱桃木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_HYPHAE_Four_Grid_Cabinet, "绯红木四格柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANKS_Four_Grid_Cabinet, "绯红木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_HYPHAE_Four_Grid_Cabinet, "诡异木材四格柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANKS_Four_Grid_Cabinet, "诡异木板四格柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_BLOCK_Four_Grid_Cabinet, "竹木四格柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANKS_Four_Grid_Cabinet, "竹木板四格柜");

        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANK_Glass_TRIPLE_CABINET, "橡木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.OAK_WOOD_Glass_TRIPLE_CABINET, "橡木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANK_Glass_TRIPLE_CABINET, "苍白橡木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_WOOD_Glass_TRIPLE_CABINET, "苍白橡木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANK_Glass_TRIPLE_CABINET, "云杉木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_WOOD_Glass_TRIPLE_CABINET, "云杉木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANK_Glass_TRIPLE_CABINET, "桦木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_WOOD_Glass_TRIPLE_CABINET, "桦木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANK_Glass_TRIPLE_CABINET, "丛林木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_WOOD_Glass_TRIPLE_CABINET, "丛林木制玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANK_Glass_TRIPLE_CABINET, "金合欢木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_WOOD_Glass_TRIPLE_CABINET, "金合欢木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANK_Glass_TRIPLE_CABINET, "深色橡木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_WOOD_Glass_TRIPLE_CABINET, "深色橡木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANK_Glass_TRIPLE_CABINET, "红树林木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_WOOD_Glass_TRIPLE_CABINET, "红树林木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANK_Glass_TRIPLE_CABINET, "樱桃木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_WOOD_Glass_TRIPLE_CABINET, "樱桃木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANK_Glass_TRIPLE_CABINET, "竹木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_WOOD_Glass_TRIPLE_CABINET, "竹木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANK_Glass_TRIPLE_CABINET, "绯红木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_WOOD_Glass_TRIPLE_CABINET, "绯红木玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANK_Glass_TRIPLE_CABINET, "诡异木板玻璃三格柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_WOOD_Glass_TRIPLE_CABINET, "诡异木玻璃门三格柜");

        translationBuilder.add(MapleFurnitureBlocks.OAK_WOOD_Glass_Four_Grid_Cabinet, "橡木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANKS_Glass_Four_Grid_Cabinet, "橡木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_WOOD_Glass_Four_Grid_Cabinet, "苍白橡木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANKS_Glass_Four_Grid_Cabinet, "苍白橡木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_WOOD_Glass_Four_Grid_Cabinet, "云杉木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANKS_Glass_Four_Grid_Cabinet, "云杉木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_WOOD_Glass_Four_Grid_Cabinet, "桦木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANKS_Glass_Four_Grid_Cabinet, "桦木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_WOOD_Glass_Four_Grid_Cabinet, "丛林木制玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANKS_Glass_Four_Grid_Cabinet, "丛林木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_WOOD_Glass_Four_Grid_Cabinet, "金合欢木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANKS_Glass_Four_Grid_Cabinet, "金合欢木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_WOOD_Glass_Four_Grid_Cabinet, "深色橡木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANKS_Glass_Four_Grid_Cabinet, "深色橡木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_WOOD_Glass_Four_Grid_Cabinet, "红树林木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANKS_Glass_Four_Grid_Cabinet, "红树林木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_WOOD_Glass_Four_Grid_Cabinet, "樱桃木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANKS_Glass_Four_Grid_Cabinet, "樱桃木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_HYPHAE_Glass_Four_Grid_Cabinet, "绯红木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANKS_Glass_Four_Grid_Cabinet, "绯红木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_HYPHAE_Glass_Four_Grid_Cabinet, "诡异木材玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANKS_Glass_Four_Grid_Cabinet, "诡异木板玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_BLOCK_Glass_Four_Grid_Cabinet, "竹木玻璃门四格柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANKS_Glass_Four_Grid_Cabinet, "竹木板玻璃门四格柜");

        translationBuilder.add(MapleFurnitureBlocks.OAK_WOOD_Wall_Cabinet, "橡树木壁柜");
        translationBuilder.add(MapleFurnitureBlocks.OAK_PLANKS_Wall_Cabinet, "橡木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_WOOD_Wall_Cabinet, "苍白橡木墙柜");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_PLANKS_Wall_Cabinet, "苍白橡木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_WOOD_Wall_Cabinet, "云杉木壁柜");
        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_PLANKS_Wall_Cabinet, "云杉木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_WOOD_Wall_Cabinet, "桦木墙柜");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_PLANKS_Wall_Cabinet, "桦木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_WOOD_Wall_Cabinet, "丛林木墙柜");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_PLANKS_Wall_Cabinet, "丛林木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_WOOD_Wall_Cabinet, "金合欢木壁柜");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_PLANKS_Wall_Cabinet, "金合欢木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_WOOD_Wall_Cabinet, "深色橡木壁柜");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_PLANKS_Wall_Cabinet, "深色橡木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_WOOD_Wall_Cabinet, "红树林木墙柜");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_PLANKS_Wall_Cabinet, "红树林木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_WOOD_Wall_Cabinet, "樱桃木壁柜");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_PLANKS_Wall_Cabinet, "樱桃木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_HYPHAE_Wall_Cabinet, "绯红木墙柜");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_PLANKS_Wall_Cabinet, "绯红木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_HYPHAE_Wall_Cabinet, "诡异木壁柜");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_PLANKS_Wall_Cabinet, "诡异木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_BLOCK_Wall_Cabinet, "竹木壁柜");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_PLANKS_Wall_Cabinet, "竹木板壁柜");
        translationBuilder.add(MapleFurnitureBlocks.WHITE_Wall_CABINET, "白色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.ORANGE_Wall_CABINET, "橙色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.MAGENTA_Wall_CABINET, "品红色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.LIGHT_BLUE_Wall_CABINET, "淡蓝色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.YELLOW_Wall_CABINET, "黄墙柜");
        translationBuilder.add(MapleFurnitureBlocks.LIME_Wall_CABINET, "石灰壁柜");
        translationBuilder.add(MapleFurnitureBlocks.PINK_Wall_CABINET, "粉红色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.GRAY_Wall_CABINET, "灰色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.LIGHT_GRAY_Wall_CABINET, "淡灰色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.CYAN_Wall_CABINET, "青色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.PURPLE_Wall_CABINET, "紫色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.BLUE_Wall_CABINET, "蓝色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.BROWN_Wall_CABINET, "棕色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.GREEN_Wall_CABINET, "绿墙柜");
        translationBuilder.add(MapleFurnitureBlocks.RED_Wall_CABINET, "红色壁柜");
        translationBuilder.add(MapleFurnitureBlocks.BLACK_Wall_CABINET, "黑色壁柜");

        translationBuilder.add(MapleFurnitureBlocks.SPRUCE_BOOKSHELF, "云杉书架");
        translationBuilder.add(MapleFurnitureBlocks.BIRCH_BOOKSHELF, "桦木书架");
        translationBuilder.add(MapleFurnitureBlocks.JUNGLE_BOOKSHELF, "丛林木书架");
        translationBuilder.add(MapleFurnitureBlocks.ACACIA_BOOKSHELF, "金合欢木书架");
        translationBuilder.add(MapleFurnitureBlocks.DARK_OAK_BOOKSHELF, "深色橡木书架");
        translationBuilder.add(MapleFurnitureBlocks.MANGROVE_BOOKSHELF, "红树林书架");
        translationBuilder.add(MapleFurnitureBlocks.CHERRY_BOOKSHELF, "樱桃木书架");
        translationBuilder.add(MapleFurnitureBlocks.BAMBOO_BOOKSHELF, "竹木书架");
        translationBuilder.add(MapleFurnitureBlocks.CRIMSON_BOOKSHELF, "绯红木书架");
        translationBuilder.add(MapleFurnitureBlocks.WARPED_BOOKSHELF, "诡异木书架");
        translationBuilder.add(MapleFurnitureBlocks.PALE_OAK_BOOKSHELF, "苍白橡木书架");

        translationBuilder.add(MapleFurnitureBlocks.WHITE_Ceiling_Lamp, "白色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.ORANGE_Ceiling_Lamp, "橙色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.MAGENTA_Ceiling_Lamp, "品红色天花板");
        translationBuilder.add(MapleFurnitureBlocks.LIGHT_BLUE_Ceiling_Lamp, "淡蓝色天花板");
        translationBuilder.add(MapleFurnitureBlocks.YELLOW_Ceiling_Lamp, "黄色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.LIME_Ceiling_Lamp, "石灰天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.PINK_Ceiling_Lamp, "粉红色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.GRAY_Ceiling_Lamp, "灰色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.LIGHT_GRAY_Ceiling_Lamp, "淡灰色天花板");
        translationBuilder.add(MapleFurnitureBlocks.CYAN_Ceiling_Lamp, "青色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.PURPLE_Ceiling_Lamp, "紫色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.BLUE_Ceiling_Lamp, "蓝色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.BROWN_Ceiling_Lamp, "棕色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.GREEN_Ceiling_Lamp, "绿色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.RED_Ceiling_Lamp, "红色天花板灯");
        translationBuilder.add(MapleFurnitureBlocks.BLACK_Ceiling_Lamp, "黑色天花板灯");

        translationBuilder.add(FurnitureStrings.Kitchen_Sink,"厨房水槽");
        translationBuilder.add(FurnitureStrings.Bedside_Cabinet,"床头柜");
        translationBuilder.add(FurnitureStrings.Cabinet,"柜子");
        translationBuilder.add(FurnitureStrings.Drawer,"抽屉");
        translationBuilder.add(FurnitureStrings.Desk_Cabinet,"桌柜");
        translationBuilder.add(FurnitureStrings.Fridge,"冰箱");
        translationBuilder.add(FurnitureStrings.Kitchen_Cabinet,"厨柜");
        translationBuilder.add(FurnitureStrings.Oven,"烤箱");
        translationBuilder.add(FurnitureStrings.TV_Stand,"电视柜");
        translationBuilder.add(FurnitureStrings.Wall_Cabinet,"壁柜");

        try {
            Path existingFilePath = dataOutput.getModContainer().findPath("assets/skniro_furniture/lang/zh_cn.existing.json").get();
            translationBuilder.add(existingFilePath);
        } catch (Exception e) {
            throw new RuntimeException("Failed to add existing language file!", e);
        }
    }
}
