package com.skniro.maple.datagen;

import com.skniro.maple.Maple;
import com.skniro.maple.block.*;
import com.skniro.maple.item.MapleItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;

import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;

public class MapleEnglishLanguageProvider extends FabricLanguageProvider {
    public MapleEnglishLanguageProvider(FabricDataOutput dataGenerator, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup){
        super(dataGenerator,"en_us", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add(Maple.Maple_Group_Furniture,"Maple Furniture");

        //Cushion
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_WHITE, "White Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_ORANGE, "Orange Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_MAGENTA, "Magenta Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_LIGHT_BLUE, "Light Blue Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_YELLOW, "Yellow Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_LIME, "Lime Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_PINK, "Pink Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_GRAY, "Gray Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_LIGHT_GRAY, "Light Gray Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_CYAN, "Cyan Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_PURPLE, "Purple Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_BLUE, "Blue Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_BROWN, "Brown Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_GREEN, "Green Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_RED, "Red Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_OAK_BLACK, "Black Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_WHITE, "White Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_ORANGE, "Orange Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_MAGENTA, "Magenta Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_LIGHT_BLUE, "Light Blue Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_YELLOW, "Yellow Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_LIME, "Lime Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_PINK, "Pink Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_GRAY, "Gray Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_LIGHT_GRAY, "Light Gray Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_CYAN, "Cyan Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_PURPLE, "Purple Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_BLUE, "Blue Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_BROWN, "Brown Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_GREEN, "Green Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_RED, "Red Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_SPRUCE_BLACK, "Black Spruce Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_WHITE, "White Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_ORANGE, "Orange Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_MAGENTA, "Magenta Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_LIGHT_BLUE, "Light Blue Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_YELLOW, "Yellow Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_LIME, "Lime Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_PINK, "Pink Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_GRAY, "Gray Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_LIGHT_GRAY, "Light Gray Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_CYAN, "Cyan Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_PURPLE, "Purple Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_BLUE, "Blue Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_BROWN, "Brown Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_GREEN, "Green Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_RED, "Red Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BIRCH_BLACK, "Black Birch Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_YELLOW, "Yellow Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_LIME, "Lime Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_PINK, "Pink Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_GRAY, "Gray Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_LIGHT_GRAY, "Light Gray Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_CYAN, "Cyan Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_PURPLE, "Purple Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_BLUE, "Blue Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_BROWN, "Brown Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_GREEN, "Green Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_RED, "Red Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_BLACK, "Black Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_WHITE,"White Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_ORANGE,"Orange Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_MAGENTA,"Magenta Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_JUNGLE_LIGHT_BLUE,"Magenta Jungle Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_WHITE, "White Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_ORANGE, "Orange Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_MAGENTA, "Magenta Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_LIGHT_BLUE, "Light Blue Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_YELLOW, "Yellow Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_LIME, "Lime Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_PINK, "Pink Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_GRAY, "Gray Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_LIGHT_GRAY, "Light Gray Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_CYAN, "Cyan Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_PURPLE, "Purple Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_BLUE, "Blue Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_BROWN, "Brown Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_GREEN, "Green Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_RED, "Red Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_ACACIA_BLACK, "Black Acacia Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_WHITE, "White Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_ORANGE, "Orange Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_MAGENTA, "Magenta Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIGHT_BLUE, "Light Blue Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_YELLOW, "Yellow Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIME, "Lime Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_PINK, "Pink Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_GRAY, "Gray Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_LIGHT_GRAY, "Light Gray Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_CYAN, "Cyan Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_PURPLE, "Purple Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_BLUE, "Blue Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_BROWN, "Brown Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_GREEN, "Green Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_RED, "Red Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_DARK_OAK_BLACK, "Black Dark Oak Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_WHITE, "White Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_ORANGE, "Orange Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_MAGENTA, "Magenta Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_LIGHT_BLUE, "Light Blue Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_YELLOW, "Yellow Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_LIME, "Lime Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_PINK, "Pink Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_GRAY, "Gray Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_LIGHT_GRAY, "Light Gray Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_CYAN, "Cyan Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_PURPLE, "Purple Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_BLUE, "Blue Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_BROWN, "Brown Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_GREEN, "Green Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_RED, "Red Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CRIMSON_BLACK, "Black Crimson Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_WHITE, "White Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_ORANGE, "Orange Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_MAGENTA, "Magenta Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_LIGHT_BLUE, "Light Blue Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_YELLOW, "Yellow Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_LIME, "Lime Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_PINK, "Pink Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_GRAY, "Gray Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_LIGHT_GRAY, "Light Gray Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_CYAN, "Cyan Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_PURPLE, "Purple Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_BLUE, "Blue Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_BROWN, "Brown Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_GREEN, "Green Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_RED, "Red Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_WARPED_BLACK, "Black Warped Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_WHITE, "White Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_ORANGE, "Orange Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_MAGENTA, "Magenta Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_LIGHT_BLUE, "Light Blue Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_YELLOW, "Yellow Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_LIME, "Lime Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_PINK, "Pink Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_GRAY, "Gray Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_LIGHT_GRAY, "Light Gray Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_CYAN, "Cyan Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_PURPLE, "Purple Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_BLUE, "Blue Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_BROWN, "Brown Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_GREEN, "Green Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_RED, "Red Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MANGROVE_BLACK, "Black Mangrove Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_WHITE, "White Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_ORANGE, "Orange Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_MAGENTA, "Magenta Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_LIGHT_BLUE, "Light Blue Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_YELLOW, "Yellow Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_LIME, "Lime Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_PINK, "Pink Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_GRAY, "Gray Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_LIGHT_GRAY, "Light Gray Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_CYAN, "Cyan Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_PURPLE, "Purple Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_BLUE, "Blue Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_BROWN, "Brown Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_GREEN, "Green Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_RED, "Red Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_MAPLE_BLACK, "Black Maple Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_WHITE, "White Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_ORANGE, "Orange Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_MAGENTA, "Magenta Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_LIGHT_BLUE, "Light Blue Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_YELLOW, "Yellow Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_LIME, "Lime Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_PINK, "Pink Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_GRAY, "Gray Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_LIGHT_GRAY, "Light Gray Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_CYAN, "Cyan Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_PURPLE, "Purple Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_BLUE, "Blue Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_BROWN, "Brown Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_GREEN, "Green Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_RED, "Red Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_CHERRY_BLACK, "Black Cherry Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_WHITE, "White Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_ORANGE, "Orange Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_MAGENTA, "Magenta Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_LIGHT_BLUE, "Light Blue Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_YELLOW, "Yellow Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_LIME, "Lime Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_PINK, "Pink Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_GRAY, "Gray Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_LIGHT_GRAY, "Light Gray Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_CYAN, "Cyan Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_PURPLE, "Purple Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_BLUE, "Blue Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_BROWN, "Brown Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_GREEN, "Green Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_RED, "Red Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_GINKGO_BLACK, "Black Ginkgo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_WHITE, "White Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_ORANGE, "Orange Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_MAGENTA, "Magenta Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_LIGHT_BLUE, "Light Blue Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_YELLOW, "Yellow Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_LIME, "Lime Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_PINK, "Pink Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_GRAY, "Gray Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_LIGHT_GRAY, "Light Gray Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_CYAN, "Cyan Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_PURPLE, "Purple Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_BLUE, "Blue Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_BROWN, "Brown Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_GREEN, "Green Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_RED, "Red Bamboo Cushion");
        translationBuilder.add(MapleFurnitureBlocks.CUSHION_BAMBOO_BLACK, "Black Bamboo Cushion");

        //Table
        translationBuilder.add(MapleFurnitureBlocks.TABLE_OAK, "Oak Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_SPRUCE, "Spruce Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_BIRCH, "Birch Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_JUNGLE, "Jungle Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_ACACIA, "Acacia Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_DARK_OAK, "Dark Oak Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_CRIMSON, "Crimson Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_WARPED, "Warped Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_MANGROVE, "Mangrove Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_BAMBOO, "Bamboo Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_CHERRY, "Cherry Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_MAPLE, "Maple Table");
        translationBuilder.add(MapleFurnitureBlocks.TABLE_GINKGO, "Ginkgo Table");


        //Window
        translationBuilder.add(MapleFurnitureBlocks.Window_Wood_GINKGO, "Ginkgo Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_Wood_MAPLE, "Maple Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_OAK, "Oak Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_BIRCH, "Birch Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_SPRUCE, "Spruce Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_JUNGLE, "Jungle Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_DARK_OAK, "Dark Oak Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_ACACIA, "Acacia Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_MANGROVE, "Mangrove Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_CHERRY, "Cherry Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_CRIMSON, "Crimson Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_WOOD_WARPED, "Warped Wood Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_OAK, "Oak Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_BIRCH, "Birch Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_SPRUCE, "Spruce Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_JUNGLE, "Jungle Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_DARK_OAK, "Dark Oak Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_ACACIA, "Acacia Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_MANGROVE, "Mangrove Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_CHERRY, "Cherry Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_CRIMSON, "Crimson Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_WARPED, "Warped Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_GINKGO, "Ginkgo Plank Window");
        translationBuilder.add(MapleFurnitureBlocks.Window_PLANK_MAPLE, "Maple Plank Window");

        //CoffeeTable
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_OAK,"Oak Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_SPRUCE,"Spruce Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_BIRCH,"Birch Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_JUNGLE,"Jungle Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_ACACIA,"Acacia Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_DARK_OAK,"Dark Oak Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_CRIMSON,"Crimson Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_WARPED,"Warped Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_MANGROVE,"Mangrove Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_BAMBOO,"Bamboo Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_WOOD_CHERRY,"Cherry Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_Wood_MAPLE,"Maple Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_Wood_GINKGO,"Ginkgo Wood Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_OAK,"Oak Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_SPRUCE,"Spruce Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_BIRCH,"Birch Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_JUNGLE,"Jungle Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_ACACIA,"Acacia Plank Coffee Table");;
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_DARK_OAK,"Dark Oak Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_CRIMSON,"Crimson Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_WARPED,"Warped Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_MANGROVE,"Mangrove Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_BAMBOO,"Bamboo Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_CHERRY,"Cherry Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_MAPLE,"Maple Plank Coffee Table");
        translationBuilder.add(MapleFurnitureBlocks.Coffee_Table_PLANK_GINKGO,"Ginkgo Plank Coffee Table");

        //Chair
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_OAK,"Oak Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_SPRUCE,"Spruce Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_BIRCH,"Birch Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_JUNGLE,"Jungle Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_ACACIA,"Acacia Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_DARK_OAK,"Dark Oak Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_CRIMSON,"Crimson Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_WARPED,"Warped Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_MANGROVE,"Mangrove Wood Chair");;
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_BAMBOO,"Bamboo Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_WOOD_CHERRY,"Cherry Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_Wood_MAPLE,"Maple Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_Wood_GINKGO,"Ginkgo Wood Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_OAK,"Oak Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_SPRUCE,"Spruce Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_BIRCH,"Birch Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_JUNGLE,"Jungle Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_ACACIA,"Acacia Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_DARK_OAK,"Dark Oak Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_CRIMSON,"Crimson Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_WARPED,"Warped Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_MANGROVE,"Mangrove Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_BAMBOO,"Bamboo Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_CHERRY,"Cherry Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_MAPLE,"Maple Plank Chair");
        translationBuilder.add(MapleFurnitureBlocks.Chair_PLANK_GINKGO,"Ginkgo Plank Chair");

        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_OAK,"Oak End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_SPRUCE,"Spruce End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_BIRCH,"Birch End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_JUNGLE,"Jungle End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_ACACIA,"Acacia End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_DARK_OAK,"Dark Oak End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_CRIMSON,"Crimson End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_WARPED,"Warped End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_MANGROVE,"Mangrove End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_BAMBOO,"Bamboo End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_CHERRY,"Cherry End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_MAPLE,"Maple End Table");
        translationBuilder.add(MapleFurnitureBlocks.END_TABLE_GINKGO,"Ginkgo End Table");

        try {
            Path existingFilePath = dataOutput.getModContainer().findPath("assets/maple/lang/en_us.existing.json").get();
            translationBuilder.add(existingFilePath);
        } catch (Exception e) {
            throw new RuntimeException("Failed to add existing language file!", e);
        }
    }
}
