package com.skniro.skniro_furniture.block.entity;

import com.skniro.skniro_furniture.Furniture;
import com.skniro.skniro_furniture.block.FurnitureBedroomBlocks;
import com.skniro.skniro_furniture.block.FurnitureKitchenBlocks;
import com.skniro.skniro_furniture.block.FurnitureLivingroomBlocks;
import com.skniro.skniro_furniture.block.MapleFurnitureBlocks;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.Set;
import java.util.function.Supplier;


public class FurnitureBlockEntityType {
    public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, Furniture.MOD_ID);

    public static final Supplier<BlockEntityType<CabinetBlockEntity>> Cabinet_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("cabinet_block_entity",
                    () -> new BlockEntityType<>(CabinetBlockEntity::new,
                            Set.of(
                                    MapleFurnitureBlocks.OAK_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.OAK_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.PALE_OAK_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.PALE_OAK_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.SPRUCE_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.SPRUCE_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.BIRCH_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.BIRCH_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.JUNGLE_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.JUNGLE_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.ACACIA_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.ACACIA_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.DARK_OAK_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.DARK_OAK_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.MANGROVE_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.MANGROVE_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.CRIMSON_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.CRIMSON_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.WARPED_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.WARPED_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.CHERRY_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.CHERRY_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.BAMBOO_PLANK_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.BAMBOO_WOOD_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.OAK_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.OAK_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.PALE_OAK_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.PALE_OAK_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.SPRUCE_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.SPRUCE_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.BIRCH_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.BIRCH_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.JUNGLE_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.JUNGLE_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.ACACIA_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.ACACIA_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.DARK_OAK_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.DARK_OAK_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.MANGROVE_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.MANGROVE_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.CRIMSON_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.CRIMSON_HYPHAE_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.WARPED_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.WARPED_HYPHAE_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.CHERRY_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.CHERRY_WOOD_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.BAMBOO_PLANKS_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.BAMBOO_BLOCK_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.OAK_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.OAK_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.PALE_OAK_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.PALE_OAK_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.SPRUCE_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.SPRUCE_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.BIRCH_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.BIRCH_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.JUNGLE_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.JUNGLE_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.ACACIA_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.ACACIA_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.DARK_OAK_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.DARK_OAK_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.MANGROVE_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.MANGROVE_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.CHERRY_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.CHERRY_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.BAMBOO_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.BAMBOO_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.CRIMSON_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.CRIMSON_WOOD_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.WARPED_PLANK_Glass_TRIPLE_CABINET.get(),
                                    MapleFurnitureBlocks.WARPED_WOOD_Glass_TRIPLE_CABINET.get(),

                                    MapleFurnitureBlocks.OAK_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.OAK_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.PALE_OAK_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.PALE_OAK_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.SPRUCE_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.SPRUCE_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.BIRCH_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.BIRCH_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.JUNGLE_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.JUNGLE_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.ACACIA_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.ACACIA_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.DARK_OAK_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.DARK_OAK_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.MANGROVE_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.MANGROVE_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.CHERRY_WOOD_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.CHERRY_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.CRIMSON_HYPHAE_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.CRIMSON_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.WARPED_HYPHAE_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.WARPED_PLANKS_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.BAMBOO_BLOCK_Glass_Four_Grid_Cabinet.get(),
                                    MapleFurnitureBlocks.BAMBOO_PLANKS_Glass_Four_Grid_Cabinet.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<DrawerBlockEntity>> Drawer_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("drawer_block_entity",
                    () -> new BlockEntityType<>(DrawerBlockEntity::new,
                            Set.of(
                                    FurnitureKitchenBlocks.WHITE_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.ORANGE_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.MAGENTA_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.LIGHT_BLUE_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.YELLOW_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.LIME_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.PINK_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.GRAY_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.LIGHT_GRAY_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.CYAN_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.PURPLE_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.BLUE_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.BROWN_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.GREEN_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.RED_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.BLACK_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.OAK_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.OAK_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.SPRUCE_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.SPRUCE_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.BIRCH_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.BIRCH_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.JUNGLE_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.JUNGLE_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.ACACIA_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.ACACIA_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.MANGROVE_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.MANGROVE_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.CHERRY_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.CHERRY_WOOD_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.CRIMSON_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.CRIMSON_HYPHAE_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.WARPED_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.WARPED_HYPHAE_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.BAMBOO_PLANKS_KITCHEN_COUNTER_DRAWER.get(),
                                    FurnitureKitchenBlocks.BAMBOO_BLOCK_KITCHEN_COUNTER_DRAWER.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<BedsideCabinetBlockEntity>> Bedside_Cabinet_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("bedside_cabinet_block_entity",
                    () -> new BlockEntityType<>(BedsideCabinetBlockEntity::new,
                            Set.of(
                                    FurnitureBedroomBlocks.OAK_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.OAK_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.PALE_OAK_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.PALE_OAK_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.SPRUCE_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.SPRUCE_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.BIRCH_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.BIRCH_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.JUNGLE_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.JUNGLE_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.ACACIA_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.ACACIA_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.DARK_OAK_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.DARK_OAK_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.MANGROVE_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.MANGROVE_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.CHERRY_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.CHERRY_WOOD_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.CRIMSON_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.CRIMSON_HYPHAE_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.WARPED_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.WARPED_HYPHAE_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.BAMBOO_PLANKS_BEDSIDE_CABINET.get(),
                                    FurnitureBedroomBlocks.BAMBOO_BLOCK_BEDSIDE_CABINET.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<KitchenCabinetBlockEntity>> Kitchen_Cabinet_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("kitchen_cabinet_block_entity",
                    () -> new BlockEntityType<>(KitchenCabinetBlockEntity::new,
                            Set.of(
                                    FurnitureKitchenBlocks.OAK_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.OAK_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.SPRUCE_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.SPRUCE_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.BIRCH_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.BIRCH_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.JUNGLE_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.JUNGLE_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.ACACIA_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.ACACIA_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.MANGROVE_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.MANGROVE_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.CHERRY_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.CHERRY_WOOD_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.CRIMSON_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.CRIMSON_HYPHAE_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.WARPED_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.WARPED_HYPHAE_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.BAMBOO_PLANKS_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.BAMBOO_BLOCK_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.WHITE_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.ORANGE_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.MAGENTA_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.LIGHT_BLUE_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.YELLOW_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.LIME_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.PINK_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.GRAY_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.LIGHT_GRAY_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.CYAN_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.PURPLE_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.BLUE_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.BROWN_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.GREEN_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.RED_KITCHEN_CABINET.get(),
                                    FurnitureKitchenBlocks.BLACK_KITCHEN_CABINET.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<DeskCabinetBlockEntity>> Desk_Cabinet_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("desk_cabinet_block_entity",
                    () -> new BlockEntityType<>(DeskCabinetBlockEntity::new,
                            Set.of(
                                    FurnitureBedroomBlocks.OAK_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.OAK_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.PALE_OAK_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.PALE_OAK_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.SPRUCE_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.SPRUCE_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.BIRCH_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.BIRCH_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.JUNGLE_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.JUNGLE_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.ACACIA_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.ACACIA_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.DARK_OAK_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.DARK_OAK_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.MANGROVE_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.MANGROVE_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.CHERRY_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.CHERRY_WOOD_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.CRIMSON_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.CRIMSON_HYPHAE_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.WARPED_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.WARPED_HYPHAE_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.BAMBOO_PLANKS_Desk_CABINET.get(),
                                    FurnitureBedroomBlocks.BAMBOO_BLOCK_Desk_CABINET.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<OvenBlockEntity>> OVEN_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("oven_block_entity",
                    () -> new BlockEntityType<>(OvenBlockEntity::new,
                            Set.of(
                                    FurnitureKitchenBlocks.OAK_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.OAK_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.SPRUCE_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.SPRUCE_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.BIRCH_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.BIRCH_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.JUNGLE_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.JUNGLE_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.ACACIA_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.ACACIA_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.MANGROVE_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.MANGROVE_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.CHERRY_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.CHERRY_WOOD_OVEN.get(),
                                    FurnitureKitchenBlocks.CRIMSON_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.CRIMSON_HYPHAE_OVEN.get(),
                                    FurnitureKitchenBlocks.WARPED_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.WARPED_HYPHAE_OVEN.get(),
                                    FurnitureKitchenBlocks.BAMBOO_PLANKS_OVEN.get(),
                                    FurnitureKitchenBlocks.BAMBOO_BLOCK_OVEN.get(),
                                    FurnitureKitchenBlocks.WHITE_OVEN.get(),
                                    FurnitureKitchenBlocks.ORANGE_OVEN.get(),
                                    FurnitureKitchenBlocks.MAGENTA_OVEN.get(),
                                    FurnitureKitchenBlocks.LIGHT_BLUE_OVEN.get(),
                                    FurnitureKitchenBlocks.YELLOW_OVEN.get(),
                                    FurnitureKitchenBlocks.LIME_OVEN.get(),
                                    FurnitureKitchenBlocks.PINK_OVEN.get(),
                                    FurnitureKitchenBlocks.GRAY_OVEN.get(),
                                    FurnitureKitchenBlocks.LIGHT_GRAY_OVEN.get(),
                                    FurnitureKitchenBlocks.CYAN_OVEN.get(),
                                    FurnitureKitchenBlocks.PURPLE_OVEN.get(),
                                    FurnitureKitchenBlocks.BLUE_OVEN.get(),
                                    FurnitureKitchenBlocks.BROWN_OVEN.get(),
                                    FurnitureKitchenBlocks.GREEN_OVEN.get(),
                                    FurnitureKitchenBlocks.RED_OVEN.get(),
                                    FurnitureKitchenBlocks.BLACK_OVEN.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<WallCabinetBlockEntity>> Wall_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("wall_block_entity",
                    () -> new BlockEntityType<>(WallCabinetBlockEntity::new,
                            Set.of(
                                    MapleFurnitureBlocks.OAK_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.OAK_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.PALE_OAK_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.PALE_OAK_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.SPRUCE_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.SPRUCE_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.BIRCH_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.BIRCH_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.JUNGLE_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.JUNGLE_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.ACACIA_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.ACACIA_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.DARK_OAK_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.DARK_OAK_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.MANGROVE_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.MANGROVE_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.CRIMSON_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.CRIMSON_HYPHAE_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.WARPED_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.WARPED_HYPHAE_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.CHERRY_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.CHERRY_WOOD_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.BAMBOO_PLANKS_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.BAMBOO_BLOCK_Wall_Cabinet.get(),
                                    MapleFurnitureBlocks.WHITE_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.ORANGE_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.MAGENTA_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.LIGHT_BLUE_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.YELLOW_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.LIME_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.PINK_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.GRAY_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.LIGHT_GRAY_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.CYAN_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.PURPLE_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.BLUE_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.BROWN_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.GREEN_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.RED_Wall_CABINET.get(),
                                    MapleFurnitureBlocks.BLACK_Wall_CABINET.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<TvStandBlockEntity>> TV_Stand_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("tv_stand_block_entity",
                    () -> new BlockEntityType<>(TvStandBlockEntity::new,
                            Set.of(
                                    FurnitureLivingroomBlocks.OAK_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.OAK_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.PALE_OAK_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.PALE_OAK_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.SPRUCE_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.SPRUCE_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.BIRCH_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.BIRCH_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.JUNGLE_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.JUNGLE_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.ACACIA_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.ACACIA_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.DARK_OAK_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.DARK_OAK_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.MANGROVE_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.MANGROVE_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.CHERRY_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.CHERRY_WOOD_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.CRIMSON_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.CRIMSON_HYPHAE_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.WARPED_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.WARPED_HYPHAE_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.BAMBOO_PLANKS_TV_STAND.get(),
                                    FurnitureLivingroomBlocks.BAMBOO_BLOCK_TV_STAND.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<FridgeBlockEntity>> Fridge_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("fridge_block_entity",
                    () -> new BlockEntityType<>(FridgeBlockEntity::new,
                            Set.of(
                                    FurnitureKitchenBlocks.WHITE_Fridge.get(),
                                    FurnitureKitchenBlocks.ORANGE_Fridge.get(),
                                    FurnitureKitchenBlocks.MAGENTA_Fridge.get(),
                                    FurnitureKitchenBlocks.LIGHT_BLUE_Fridge.get(),
                                    FurnitureKitchenBlocks.YELLOW_Fridge.get(),
                                    FurnitureKitchenBlocks.LIME_Fridge.get(),
                                    FurnitureKitchenBlocks.PINK_Fridge.get(),
                                    FurnitureKitchenBlocks.GRAY_Fridge.get(),
                                    FurnitureKitchenBlocks.LIGHT_GRAY_Fridge.get(),
                                    FurnitureKitchenBlocks.CYAN_Fridge.get(),
                                    FurnitureKitchenBlocks.PURPLE_Fridge.get(),
                                    FurnitureKitchenBlocks.BLUE_Fridge.get(),
                                    FurnitureKitchenBlocks.BROWN_Fridge.get(),
                                    FurnitureKitchenBlocks.GREEN_Fridge.get(),
                                    FurnitureKitchenBlocks.RED_Fridge.get(),
                                    FurnitureKitchenBlocks.BLACK_Fridge.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<KitchenSinkBlockEntity>> Kitchen_Sink_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("kitchen_sink_block_entity",
                    () -> new BlockEntityType<>(KitchenSinkBlockEntity::new,
                            Set.of(
                                    FurnitureKitchenBlocks.WHITE_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.ORANGE_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.MAGENTA_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.LIGHT_BLUE_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.YELLOW_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.LIME_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.PINK_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.GRAY_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.LIGHT_GRAY_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.CYAN_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.PURPLE_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.BLUE_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.BROWN_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.GREEN_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.RED_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.BLACK_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.OAK_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.OAK_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.SPRUCE_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.SPRUCE_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.BIRCH_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.BIRCH_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.JUNGLE_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.JUNGLE_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.ACACIA_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.ACACIA_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.MANGROVE_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.MANGROVE_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.CHERRY_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.CHERRY_WOOD_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.CRIMSON_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.CRIMSON_HYPHAE_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.WARPED_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.WARPED_HYPHAE_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.BAMBOO_PLANKS_KITCHEN_SINK.get(),
                                    FurnitureKitchenBlocks.BAMBOO_BLOCK_KITCHEN_SINK.get()
                            )
                    )
            );

    public static final Supplier<BlockEntityType<PlateBlockEntity>> Plate_BLOCK_ENTITY =
            BLOCK_ENTITIES.register("plate_block_entity",
                    () -> new BlockEntityType<>(PlateBlockEntity::new,
                            Set.of(
                                    FurnitureKitchenBlocks.WHITE_Plate.get(),
                                    FurnitureKitchenBlocks.ORANGE_Plate.get(),
                                    FurnitureKitchenBlocks.MAGENTA_Plate.get(),
                                    FurnitureKitchenBlocks.LIGHT_BLUE_Plate.get(),
                                    FurnitureKitchenBlocks.YELLOW_Plate.get(),
                                    FurnitureKitchenBlocks.LIME_Plate.get(),
                                    FurnitureKitchenBlocks.PINK_Plate.get(),
                                    FurnitureKitchenBlocks.GRAY_Plate.get(),
                                    FurnitureKitchenBlocks.LIGHT_GRAY_Plate.get(),
                                    FurnitureKitchenBlocks.CYAN_Plate.get(),
                                    FurnitureKitchenBlocks.PURPLE_Plate.get(),
                                    FurnitureKitchenBlocks.BLUE_Plate.get(),
                                    FurnitureKitchenBlocks.BROWN_Plate.get(),
                                    FurnitureKitchenBlocks.GREEN_Plate.get(),
                                    FurnitureKitchenBlocks.RED_Plate.get(),
                                    FurnitureKitchenBlocks.BLACK_Plate.get(),
                                    FurnitureKitchenBlocks.OAK_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.OAK_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.PALE_OAK_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.SPRUCE_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.SPRUCE_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.BIRCH_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.BIRCH_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.JUNGLE_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.JUNGLE_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.ACACIA_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.ACACIA_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.DARK_OAK_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.MANGROVE_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.MANGROVE_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.CHERRY_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.CHERRY_WOOD_Plate.get(),
                                    FurnitureKitchenBlocks.CRIMSON_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.CRIMSON_HYPHAE_Plate.get(),
                                    FurnitureKitchenBlocks.WARPED_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.WARPED_HYPHAE_Plate.get(),
                                    FurnitureKitchenBlocks.BAMBOO_PLANKS_Plate.get(),
                                    FurnitureKitchenBlocks.BAMBOO_BLOCK_Plate.get()
                            )
                    )
            );

    public static void registerMapleBlockEntityType(IEventBus eventBus) {
        BLOCK_ENTITIES.register(eventBus);
    }
}
